import { useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AuthTextInput } from "../../components/AuthTextInput";
import { useAppTheme } from "../../constants/theme";
import { createAdminCourse, getAdminCatalog, updateAdminCourse } from "../../lib/api";
import { useAuthStore } from "../../stores/auth-store";
import { RetryButton } from "../../components/RetryButton";

export default function AdminCoursesScreen() {
  const theme = useAppTheme(); const styles = createStyles(theme); const token = useAuthStore((state) => state.token); const client = useQueryClient();
  const catalog = useQuery({ queryKey: ["admin", "catalog"], queryFn: () => getAdminCatalog(token as string), enabled: Boolean(token) });
  const [editingId, setEditingId] = useState<number | null>(null); const [code, setCode] = useState(""); const [name, setName] = useState(""); const [semester, setSemester] = useState(""); const [sections, setSections] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  function beginEdit(course: NonNullable<typeof catalog.data>["courses"][number]) { setEditingId(course.course_id); setCode(course.course_code); setName(course.course_name); setSemester(course.semester?.toString() ?? ""); setSections(""); setError(null); }
  function reset() { setEditingId(null); setCode(""); setName(""); setSemester(""); setSections(""); setError(null); }
  async function save() { setSaving(true); setError(null); try { const sectionList = sections.split(",").map((item) => item.trim()).filter(Boolean); if (editingId) await updateAdminCourse(token as string, editingId, { course_code: code, course_name: name, semester: semester ? Number(semester) : null, ...(sectionList.length ? { add_sections: sectionList } : {}) }); else await createAdminCourse(token as string, { course_code: code, course_name: name, semester: semester ? Number(semester) : null, sections: sectionList }); await client.invalidateQueries({ queryKey: ["admin"] }); reset(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save course."); } finally { setSaving(false); } }
  if (catalog.isFetching && !catalog.data) return <View style={styles.centered}><ActivityIndicator color={theme.colors.black} /></View>;
  if (catalog.error) return <View style={styles.centered}><Text style={styles.title}>Unable to load courses</Text><RetryButton onPress={() => void catalog.refetch()} /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backLabel}>‹ Admin</Text></Pressable><Text style={styles.title}>{editingId ? "Edit course" : "Course management"}</Text><View style={styles.form}><AuthTextInput onChangeText={setCode} placeholder="Course code (e.g. CS101)" value={code} /><AuthTextInput onChangeText={setName} placeholder="Course name" value={name} /><AuthTextInput keyboardType="number-pad" onChangeText={setSemester} placeholder="Semester (optional)" value={semester} /><AuthTextInput onChangeText={setSections} placeholder={editingId ? "Add sections, comma-separated" : "Sections, comma-separated (e.g. 287, 591)"} value={sections} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={saving} onPress={() => void save()} style={styles.primary}><Text style={styles.primaryLabel}>{saving ? "Saving..." : editingId ? "Save changes" : "Create course"}</Text></Pressable>{editingId ? <Pressable onPress={reset} style={styles.secondary}><Text style={styles.secondaryLabel}>Cancel edit</Text></Pressable> : null}</View><Text style={styles.sectionTitle}>Existing courses</Text>{catalog.isLoading ? <ActivityIndicator color={theme.colors.black} /> : null}{!catalog.isLoading && catalog.data?.courses.length === 0 ? <Text style={styles.empty}>No courses yet. Create one to get started.</Text> : null}{catalog.data?.courses.map((course) => <Pressable key={course.course_id} onPress={() => beginEdit(course)} style={styles.card}><Text style={styles.cardTitle}>{course.course_code} · {course.course_name}</Text><Text style={styles.cardMeta}>Sections: {course.sections.join(", ") || "None"}</Text><Text style={styles.edit}>Edit / add section</Text></Pressable>)}</ScrollView>;
}
const createStyles = (theme: ReturnType<typeof useAppTheme>) => StyleSheet.create({ screen: { backgroundColor: theme.colors.white, flex: 1 }, content: { padding: theme.spacing.xl, paddingBottom: theme.spacing.huge }, centered: { alignItems: "center", backgroundColor: theme.colors.white, flex: 1, justifyContent: "center", padding: theme.spacing.xl }, back: { alignSelf: "flex-start", justifyContent: "center", minHeight: 44 }, backLabel: { color: theme.colors.grey700, ...theme.typography.body }, title: { color: theme.colors.black, ...theme.typography.display }, form: { gap: theme.spacing.md, marginTop: theme.spacing.xl }, primary: { alignItems: "center", backgroundColor: theme.colors.orange, borderRadius: theme.radius.button, justifyContent: "center", minHeight: 52 }, primaryLabel: { color: theme.colors.onAccent, ...theme.typography.body, fontFamily: theme.fontFamily.semibold }, secondary: { alignItems: "center", borderColor: theme.colors.grey300, borderRadius: theme.radius.button, borderWidth: 1, justifyContent: "center", minHeight: 48 }, secondaryLabel: { color: theme.colors.black, ...theme.typography.body }, error: { color: theme.colors.red, ...theme.typography.label }, empty: { color: theme.colors.grey600, marginTop: theme.spacing.md, ...theme.typography.body }, sectionTitle: { color: theme.colors.black, marginTop: theme.spacing.xxxl, ...theme.typography.heading }, card: { backgroundColor: theme.colors.grey50, borderColor: theme.colors.grey200, borderRadius: theme.radius.card, borderWidth: 1, marginTop: theme.spacing.md, minHeight: 88, padding: theme.spacing.lg }, cardTitle: { color: theme.colors.black, ...theme.typography.body, fontFamily: theme.fontFamily.semibold }, cardMeta: { color: theme.colors.grey600, marginTop: theme.spacing.xs, ...theme.typography.label }, edit: { color: theme.colors.orange, marginTop: theme.spacing.sm, ...theme.typography.label, fontFamily: theme.fontFamily.semibold } });
