import { useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AdminSelect } from "../../components/AdminSelect";
import { AuthTextInput } from "../../components/AuthTextInput";
import { RetryButton } from "../../components/RetryButton";
import { useAppTheme } from "../../constants/theme";
import { createAdminUser, enrollAdminStudent, getAdminCatalog } from "../../lib/api";
import { useAuthStore } from "../../stores/auth-store";

export default function AdminStudentsScreen() {
  const theme = useAppTheme(); const styles = createStyles(theme); const token = useAuthStore((state) => state.token); const client = useQueryClient(); const catalog = useQuery({ queryKey: ["admin", "catalog"], queryFn: () => getAdminCatalog(token as string), enabled: Boolean(token) });
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [studentNumber, setStudentNumber] = useState(""); const [department, setDepartment] = useState(""); const [semester, setSemester] = useState(""); const [studentId, setStudentId] = useState(""); const [courseSection, setCourseSection] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const sectionOptions = catalog.data?.courses.flatMap((course) => course.sections.map((section) => ({ value: `${course.course_id}:${section}`, label: `${course.course_code} — Section ${section}` }))) ?? [];
  async function createStudent() { setBusy(true); setError(null); try { await createAdminUser(token as string, { name, email, password, role: "student", student_id: studentNumber, department, semester: Number(semester) }); await client.invalidateQueries({ queryKey: ["admin"] }); setName(""); setEmail(""); setPassword(""); setStudentNumber(""); setDepartment(""); setSemester(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create student."); } finally { setBusy(false); } }
  async function enroll() { if (!studentId || !courseSection) return; setBusy(true); setError(null); try { const [courseId, section] = courseSection.split(":"); await enrollAdminStudent(token as string, { student_id: Number(studentId), course_id: Number(courseId), section }); setCourseSection(""); await client.invalidateQueries({ queryKey: ["admin"] }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to enroll student."); } finally { setBusy(false); } }
  if (catalog.isFetching && !catalog.data) return <View style={styles.centered}><ActivityIndicator color={theme.colors.black} /></View>;
  if (catalog.error) return <View style={styles.centered}><Text style={styles.title}>Unable to load catalog</Text><RetryButton onPress={() => void catalog.refetch()} /></View>;
  const students = catalog.data?.students ?? [];
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backLabel}>‹ Admin</Text></Pressable><Text style={styles.title}>Student management</Text><Text style={styles.heading}>Create student</Text><View style={styles.form}><AuthTextInput onChangeText={setName} placeholder="Full name" value={name} /><AuthTextInput autoCapitalize="none" keyboardType="email-address" onChangeText={setEmail} placeholder="Email" value={email} /><AuthTextInput onChangeText={setPassword} placeholder="Password" secureTextEntry value={password} /><AuthTextInput onChangeText={setStudentNumber} placeholder="University student ID" value={studentNumber} /><AuthTextInput onChangeText={setDepartment} placeholder="Department" value={department} /><AuthTextInput keyboardType="number-pad" onChangeText={setSemester} placeholder="Semester" value={semester} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={busy || !semester} onPress={() => void createStudent()} style={styles.primary}><Text style={styles.primaryLabel}>{busy ? "Saving..." : "Create student"}</Text></Pressable></View><Text style={styles.heading}>Course enrollment</Text>{!catalog.isLoading && (students.length === 0 || sectionOptions.length === 0) ? <Text style={styles.empty}>Create a student and course section before making an enrollment.</Text> : null}<View style={styles.form}><AdminSelect label="Student" onChange={setStudentId} value={studentId} options={students.map((student) => ({ value: String(student.student_id), label: `${student.name} · ${student.university_student_id}` }))} /><AdminSelect label="Course-section" onChange={setCourseSection} value={courseSection} options={sectionOptions} /><Pressable disabled={busy || !studentId || !courseSection} onPress={() => void enroll()} style={styles.primary}><Text style={styles.primaryLabel}>Save enrollment</Text></Pressable></View></ScrollView>;
}
const createStyles = (theme: ReturnType<typeof useAppTheme>) => StyleSheet.create({ screen: { backgroundColor: theme.colors.white, flex: 1 }, content: { padding: theme.spacing.xl, paddingBottom: theme.spacing.huge }, centered: { alignItems: "center", backgroundColor: theme.colors.white, flex: 1, justifyContent: "center", padding: theme.spacing.xl }, back: { alignSelf: "flex-start", justifyContent: "center", minHeight: 44 }, backLabel: { color: theme.colors.grey700, ...theme.typography.body }, title: { color: theme.colors.black, ...theme.typography.display }, heading: { color: theme.colors.black, marginTop: theme.spacing.xxl, ...theme.typography.heading }, empty: { color: theme.colors.grey600, marginTop: theme.spacing.sm, ...theme.typography.body }, form: { gap: theme.spacing.md, marginTop: theme.spacing.md }, primary: { alignItems: "center", backgroundColor: theme.colors.orange, borderRadius: theme.radius.button, justifyContent: "center", minHeight: 52 }, primaryLabel: { color: theme.colors.onAccent, ...theme.typography.body, fontFamily: theme.fontFamily.semibold }, error: { color: theme.colors.red, ...theme.typography.label } });
